server:
  port: 8082


dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.heshang
  monitor:
    protocol: registry
  provider:
    timeout: 2000